# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'AWS'

steps:

  - task: CmdLine@2
    inputs:
      script: |
        docker build -t rkalluru/b48-$(appName):$(Build.BuildId) .
        docker push rkalluru/b48-$(appName):$(Build.BuildId)
    displayName: Docker Build Push

  - task: CmdLine@2
    inputs:
      script: |
        mkdir output
        cd output
        sed -e "s/BUILDNO/$(Build.BuildId)/" ../k8s/deployment.yml >deployment.yml
        sed -e "s/BUILDNO/$(Build.BuildId)/" ../k8s/service.yml >service.yml
        env
        pwd
    displayName: Update Kubernetes

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/output'
      ArtifactName: 'k8s-ouptuts'
      publishLocation: 'Container'

#- task: CmdLine@2
#  inputs:
#    script: |
#      mkdir publish
#      mv *.js publish
#      cd publish
#      az artifacts universal publish --organization https://dev.azure.com/DevOps-Batches/ --project="DevOps48" --scope project --feed RoboShop --name  $(appName) --version 1.0.$(Build.BuildId) --description "$(appName)" --path .
#  displayName: Publish Artifacts

variables:
  appName: "redis"
